version: '3.7'

services:

  portainer:
    networks:
      - overlay
    ports:
#      - ${PORTAINER_SERVER_PORT}:8000
      - ${PORTAINER_UI_PORT}:9000
    image: ${PORTAINER_IMAGE}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer-data:

networks:
  overlay: