version: '3.7'

services:
  portainer:
    image: portainer/portainer:1.23.0
    volumes:
      - portainer:/data
    environment:
      AGENT_SECRET: 0c41adac4dc4923b6878ad764b4a6f29
    networks:
      - public
      - portainer
    ports:
      - 9000:9000
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.rule: Host(`portainer.th.is`)
      traefik.http.routers.portainer.tls: "true"
      traefik.http.routers.portainer.entrypoints: https
      traefik.http.routers.portainer.service: portainer
      traefik.http.services.portainer.loadbalancer.server.port: 9000
      traefik.http.routers.portainer-http.rule: hostregexp(`{host:.+}`)
      traefik.http.routers.portainer-http.entrypoints: http
      traefik.http.routers.portainer-http.middlewares: redirect-to-https

  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_SECRET: 0c41adac4dc4923b6878ad764b4a6f29
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

volumes:
  portainer:

networks:
  public:
    external: true
  portainer:
    internal: true