version: '3.7'

services:
  proxy-socket:
    image: tecnativa/docker-socket-proxy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 20s
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - docker-socket
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  docker-socket:
    driver: overlay
    attachable: true