version: '3.7'

services:
  portainer:
    image: portainer/portainer:1.23.0
    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    environment:
      AGENT_SECRET: 0c41adac4dc4923b6878ad764b4a6f29
    networks:
      - public
      - portainer
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.rule: Host(`portainer.th.is`)
      traefik.http.routers.portainer.entrypoints: http
      traefik.http.services.portainer.loadbalancer.server.port: 9000

  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_SECRET: 0c41adac4dc4923b6878ad764b4a6f29
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

volumes:
  portainer:

networks:
  public:
    external: true
  portainer:
