version: "3.7"

x-default-opts:
  &default-opts
  deploy:
    replicas: 1
    placement:
      constraints: [node.role == manager]
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 20s

services:
  traefik:
    image: traefik:v2.1.1
    <<: *default-opts
    networks:
      - public
      - traefik-docker
    command:
      - --entrypoints.http.address=:80
      - --providers.docker
      - --providers.docker.endpoint=http://dockersocket:2375
#      - --providers.docker.swarmMode=true
      - --providers.docker.network=public
      - --providers.docker.exposedbydefault=false
      - --api.insecure
      - --api.dashboard=true # see https://docs.traefik.io/v2.0/operations/dashboard/#secure-mode for how to secure the dashboard
      - --api.debug=true # enable additional endpoints for debugging and profiling
      - --log.level=DEBUG # debug while we get it working
      - --accesslog=true
    ports:
      - 80:80
      - 443:44
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      # Dashboard
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: Host(`traefik.th.is`)
      traefik.http.routers.traefik.entrypoints: http
      traefik.http.routers.traefik.service: api@internal
#      traefik.http.routers.traefik.middlewares: authtraefik
#      Basic auth (login: user | password: password)
#      traefik.http.middlewares.authtraefik.basicauth.users: user:$$apr1$$q8eZFHjF$$Fvmkk//V6Btlaf2i/ju5n/

  whoami:
    image: containous/whoami:v1.3.0
    command:
      # It tells whoami to start listening on 8082 instead of 80
      - --port=8082
    networks:
      - public
    labels:
      traefik.enable: "true"
      traefik.http.routers.whoami.rule: Host(`whoami.th.is`)
      traefik.http.routers.whoamientrypoints: http
      traefik.http.services.whoami.loadbalancer.server.port: 8082
#      traefik.http.routers.whoami.middlewares: auth
#      Basic auth (login: user | password: password)
#      traefik.http.middlewares.auth.basicauth.users: user:$$apr1$$q8eZFHjF$$Fvmkk//V6Btlaf2i/ju5n/
    <<: *default-opts
#      resources:
#        limits:
#          cpus: '0.10'
#          memory: 32M
#        reservations:
#          cpus: '0.05'
#          memory: 10M

## https://github.com/containous/traefik/issues/4174#issuecomment-446564816:
  dockersocket:
      image: tecnativa/docker-socket-proxy
      <<: *default-opts
      networks:
        - traefik-docker
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
      environment:
        CONTAINERS: 1
        NETWORKS: 1
        SERVICES: 1
        TASKS: 1

networks:
  public:
    external: true
  traefik-docker: