version: '3.7'

services:
  portainer:
    image: portainer/portainer:1.23.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    networks:
      - public
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.rule: Host(`portainer.th.is`)
      traefik.http.routers.portainer.entrypoints: http
      traefik.http.services.portainer.loadbalancer.server.port: 9000

volumes:
  portainer:

networks:
  public:
    external: true